#!/usr/bin/env bash

# Switch to parent directory of location of script
cd "$(dirname "$BASH_SOURCE")/.."

tests=(
    check
    check_short
    range
    range_short
)
errors=0

for t in "${tests[@]}"; do
  printf "%s...\n" "$t"
  diff "test/$t.out" <("test/$t") >&2 || (( ++errors ))
done

if (( errors )); then
  printf "Failed %d of %d\n" "$errors" "${#tests[@]}" >&2
  exit 1
fi
