#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

tests=(
    check
    check_short
    range
    range_short
)
errors=0

for t in "${tests[@]}"; do
  printf "%s...\n" "$t"
  diff "test/$t.out" <("test/$t") >&2 || (( ++errors ))
done

if (( errors )); then
  printf "Failed %d of %d\n" "$errors" "${#tests[@]}" >&2
  exit 1
fi
